<?php

// code to add a vertical menu down the side of the page.
//D Waddy March 15 2009


class VerticalMenu {
    
    function xx() {
        ?>
        
        <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar nav-child-indent flex-column" data-widget="treeview" role="menu">
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/index.html" class="nav-link active">
                <i class="nav-icon fas fa-microchip"></i>
                <p>
                  Installation
                  
                </p>
              </a>

              
            </li>
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/dependencies.html" class="nav-link ">
                <i class="nav-icon fas fa-handshake"></i>
                <p>
                  Dependencies &amp; Plugins
                  
                </p>
              </a>

              
            </li>
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/layout.html" class="nav-link ">
                <i class="nav-icon fas fa-copy"></i>
                <p>
                  Layout
                  
                </p>
              </a>

              
            </li>
         
            
            

            <li class="nav-item has-treeview ">
              

              <a href="/docs/3.0/components" class="nav-link ">
                <i class="nav-icon fas fa-th"></i>
                <p>
                  Components
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>

              
                <ul class="nav nav-treeview">
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/main-header.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Main Header</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/main-sidebar.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Main Sidebar</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/control-sidebar.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Control Sidebar</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/cards.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Card</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/boxes.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Small-/ Info-Box</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/direct-chat.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Direct Chat</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/timeline.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Timeline</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/ribbons.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Ribbons</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/miscellaneous.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Miscellaneous</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/components/plugins.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Plugins</p>
                    </a>
                  </li>
                
                </ul>
              
            </li>
         
            
            

            <li class="nav-item has-treeview ">
              

              <a href="/docs/3.0/javascript" class="nav-link ">
                <i class="nav-icon fas fa-code"></i>
                <p>
                  JavaScript
                  <i class="right fas fa-angle-left"></i>
                </p>
              </a>

              
                <ul class="nav nav-treeview">
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/layout.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Layout</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/push-menu.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Push Menu</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/treeview.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Treeview</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/card-widget.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Card Widget</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/card-refresh.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>CardRefresh</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/control-sidebar.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Control Sidebar</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/direct-chat.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Direct Chat</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/todo-list.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Todo List</p>
                    </a>
                  </li>
                
                  
                  <li class="nav-item">
                    <a href="/docs/3.0/javascript/toasts.html" class="nav-link ">
                      <i class="far fa-circle nav-icon"></i>
                      <p>Toasts</p>
                    </a>
                  </li>
                
                </ul>
              
            </li>
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/browser-support.html" class="nav-link ">
                <i class="nav-icon fab fa-chrome"></i>
                <p>
                  Browser Support
                  
                </p>
              </a>

              
            </li>
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/upgrade-guide.html" class="nav-link ">
                <i class="nav-icon fas fa-hand-point-up"></i>
                <p>
                  Upgrade Guide
                  
                </p>
              </a>

              
            </li>
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/implementations.html" class="nav-link ">
                <i class="nav-icon fas fa-bookmark"></i>
                <p>
                  Implementations
                  
                </p>
              </a>

              
            </li>
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/faq.html" class="nav-link ">
                <i class="nav-icon fas fa-question-circle"></i>
                <p>
                  FAQ
                  
                </p>
              </a>

              
            </li>
         
            
            

            <li class="nav-item  ">
              

              <a href="/docs/3.0/license.html" class="nav-link ">
                <i class="nav-icon fas fa-file-alt"></i>
                <p>
                  License
                  
                </p>
              </a>

              
            </li>
         
        </ul>
      </nav>
        
       <?php
        
        
        
        
    }
    
    

    //used with adminlte
    public function createMenuList() {

        $sql = "
           With temp as (
with recursive rel_tree as (
   select pageid, title::text, parent_id,filesubdir::text,rank,filename,auto_refresh, 1 as level, array[pageid] as path_info
   from intwebsite.page 
   where parent_id = 0 AND active = true
   union all
   select c.pageid, rpad('', p.level * 2, ' ') || c.title::text, c.parent_id,c.filesubdir::text,c.rank,c.filename,c.auto_refresh, p.level + 1, p.path_info||c.pageid
   from intwebsite.page c
     join rel_tree p on c.parent_id = p.pageid  where c.active = true
)
select pageid, title,filesubdir,filename,rank,auto_refresh,level, path_info,REPLACE(path_info::text,',' || pageid::text,'') || '.' || rank::text as path_info2
from rel_tree

)
Select distinct(temp.pageid), temp.*,userid,temp.path_info[2] as two,temp.path_info[3] as three
from temp
 JOIN intwebsite.page_security ON temp.pageid=page_security.pageid
 JOIN wcauthentication.users_in_groups ON page_security.group=users_in_groups.groupid
WHERE users_in_groups.userid = '{$GLOBALS['auth']->getUsername()}' AND temp.pageid !=1
order by two,rank NULLS FIRST
       ";
        $res = $GLOBALS['pdo']->query($sql);
        $dataArr = $res->fetchAll(PDO::FETCH_ASSOC);

        //before we start, we need to find the active pages parent level, so when it comes up we can open it, this is for level 2.
        $key = array_search($_REQUEST['pageid'], array_column($dataArr, 'three'));
        $activeLevel2 = $dataArr[$key]['two'];

        
        //assume it is in order
        $prevLevel = 1;
        $level1_n = 1;
        foreach ($dataArr as $key => $vArr) {

            $vArr['title'] = trim($vArr['title']);


            if (($prevLevel < $vArr['level']) && ($vArr['level'] == 3)) {
               $out[]=  ("\t\t<ul class='nav nav-treeview'>\n\n"); //WHY IS THIS HERE>
            }

            //closing brackets
            if ($prevLevel > $vArr['level']) {
               $out[]=  ("\t\t</ul>\n\n");
            }
            if ($prevLevel > $vArr['level']) {
               $out[]=  ("\t\t</li>\n\n");
            }




            //only   a page id for the first level if it actually exists (has a file associated with it)
            if (($vArr['filename'] != null) && ($vArr['level'] == 1)) {
                //home page do nothing
            } elseif (($vArr['filename'] == '') && ($vArr['level'] == 2)) {
                $active2 = ($activeLevel2 == $vArr['two']) ? ' menu-open' : '';  //using array search logic above, see if we are in the active level 2.  
                $active2b = ($activeLevel2 == $vArr['two']) ?  'active' : '';  
                 
                $icon=null;
                $icon=VerticalMenu::iconChooser($vArr['title']);
                
                $out[]=  <<<HTML
                    <li class='nav-item has-treeview $active2'>
                        <a href='#' class="nav-link $active2b"> 
                            <i class='nav-icon fas $icon'></i> 
                            <p>{$vArr['title']}
                               
                                    <i class='right fas fa-angle-left'></i>
                            
                            </p>
                            
                              
                        </a>
                        
HTML;
       
                $level1_n++;
            } elseif (($vArr['level'] == 3)) {
                $active3 = ($_REQUEST['pageid'] == $vArr['pageid']) ?  'active' : '';      //see if we are the active page and if so add class to list to highlight it.       

                $out[]=  <<<HTML
                    <li class='nav-item'>
                        <a href="/index.php?pageid={$vArr['pageid']}" class="nav-link $active3">
                            <i class='far fa-circle nav-icon'></i><p>{$vArr['title']}</p>
                        </a>
                    </li>
HTML;
                
            } else {
                throw new Exception("Error Improper menu level, not 1,2,or 3.");
            }

            $prevLevel = $vArr['level'];
        }

        return implode($out);
    }

    /**
      get an array that list all the valid pageids this particular user can see.
     */
    public function getListofAllowedPages() {
        $sql = "SELECT DISTINCT ON (page.pageid) page.pageid,title FROM intwebsite.page
LEFT JOIN intwebsite.page_security ON page.pageid=page_security.pageid
LEFT JOIN wcauthentication.users_in_groups ON page_security.group=users_in_groups.groupid
WHERE page.active=true AND users_in_groups.userid = '{$GLOBALS['auth']->getUsername()}'";
        $res = $GLOBALS['pdo']->query($sql);
        while ($row = $res->fetch(PDO::FETCH_ASSOC)) {
            $allowedArray[] = $row['pageid'];
        }
        return $allowedArray;
    }

    /*
     * chooses a bootstrap icon class, based on header name.
     * this is kind of hackish, but keeps display stuff out of DB.
     */

    private static function iconChooser($name) {
        switch ($name) {
            case 'Reproduction':
                $class = 'fa-venus-mars';
                break;
            case 'Movement':
                $class = 'fa-truck';
                break;
            case 'Transition':
                $class = 'fa-share';
                break;
            case 'Medical':
                $class = 'fa-medkit';
                break;
            case 'Heifers':
                $class = 'fa-baby-carriage'; //baby??
                break;
            case 'Cropping':
                $class = 'fa-map';
                break;
            case 'Misc':
                $class = 'fa-question-circle';
                break;
            case 'HR':
                $class = ' fa-user';
                break;
            case 'Reports':
                $class = ' fa-chart-bar';
                break;
            case 'Nutrition':
                $class = 'fa-utensils';
                break;
            case 'Machinery':
                $class = 'fa-tractor';
                break;
            case 'Management':
                $class = ' fa-calculator';
                break;
            case 'Building':
                $class = 'fa-building';
                break;
             case 'Video':
                $class = 'fa-video';
                break;
            default:
                $class = 'fa-link';
        }
        return $class;
    }

}

//end class    
?>