<?php 
/*
Page to show video archives
*/

class VideoArchive extends BasePage {

	

	public function defaultDisplay() {
            
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=3'>Shop</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=1'>Low Group</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=4'>Maternity Pack</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=5'>Parlor Front Door Inside</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=6'>Parlor Pit</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=8'>Heifer Group</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=9'>Sort Gate</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=10'>High Group</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=11'>Heifer Barn</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=12'>Parlor Front Door Outside</a></h3>");
print("<h3><a href='http://hoth/zm/index.php?view=watch&mid=13'>151 bannister</a></h3>");



http://hoth/zm/index.php?view=watch&mid=1

   }

	


 



}//end class
?>
